/*
List<String> images = [
  "assets/image_17.jpg",
  "assets/image_16.jpg",
  "assets/image_15.jpeg",
  "assets/image_14.jpeg",
  "assets/image_13.png",
  "assets/image_12.png",
  "assets/image_11.jpg",
  "assets/image_10.jpeg",
  "assets/image_09.jpeg",
  "assets/image_08.jpg",
  "assets/image_07.jpeg",
  "assets/image_06.jpg",
  "assets/image_05.jpg",
  "assets/image_04.jpeg",
  "assets/image_03.jpg",
  "assets/image_02.jpg",
  "assets/image_01.jpg",
];

List<String> title = [
  "Us Looking Down At Everyone For Not Being Us"
  "Through Everything",
  "Being With Me",
  "Thank You For",
  "SO CUTE pt.3",
  "Oh Here Too",
  "Wow You Must Be Very Good Pillow",
  "And Here",
  "Like Here",
  "And Belong In My Arms",
  "You're A Good Pillow",
  "SO CUTE pt.2",
  "Can't Beat Your Birthday Gifts TBH",
  "Love Being Weird On Call Together",
  "SO CUTE",
  "Favourite Food Buddy",
  "Here's Some Appreciation",
];
*/

List<String> images = [
  "assets/image_16.jpg",
  "assets/image_15.jpeg",
  "assets/image_14.jpeg",
  "assets/image_13.png",
  "assets/image_12.png",
  "assets/image_11.jpg",
  "assets/image_10.jpeg",
  "assets/image_09.jpeg",
  "assets/image_08.jpg",
  "assets/image_07.jpeg",
  "assets/image_06.jpg",
  "assets/image_05.jpg",
  "assets/image_04.jpeg",
  "assets/image_03.jpg",
  "assets/image_02.jpg",
  "assets/image_01.jpg",
];

List<String> title = [
  "Through Everything",
  "Being With Me",
  "Thank You For",
  "SO CUTE pt.3",
  "Oh Here Too",
  "Wow You Must Be Very Good Pillow",
  "And Here",
  "Like Here",
  "And Belong In My Arms",
  "You're A Good Pillow",
  "SO CUTE pt.2",
  "Can't Beat Your Birthday Gifts TBH",
  "Love Being Weird On Call Together",
  "SO CUTE",
  "Favourite Food Buddy",
  "Here's Some Appreciation",
];
